name: build

on:
  push:
    tags: [v*]
    branches: [master]
  pull_request:

jobs:
  # See https://github.com/mvdan/github-actions-golang
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.14.x, 1.15.x]
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-new-combinations
        include:
          - os: windows-latest
            go-version: 1.15.x
          - os: macos-latest
            go-version: 1.15.x
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    defaults:
      run:
        working-directory: ./src/github.com/${{ github.repository }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Test
        run: go test ./...
